Enable GC on metadata server which synchronizes storage with it
kurafs/kura pull request #9
Opened 2019-02-13 17:35 UTC by arhamahmed

Garbage collection is the preferred alternative to #5 for its simplicity as per offline discussion. Transactions have the overhead of managing recovery and a WAL for which the performance gains were not enough to justify implementation.

Two new RPCs were added: one that gets all the keys in the storage server and one that forces the garbage collector to run otherwise it runs periodically (every 24 hours).

2019-02-19 17:06 UTC, irfansharif commented on cmd/metadata-server/run.go
> +	metadataServer.runGarbageCollection(context.Background())
Don't need this.

2019-02-19 17:15 UTC, irfansharif commented
`go test ./...` fails in root directory, you need to implement new interface methods on test objects.

2019-02-19 17:43 UTC, irfansharif requested changes

2019-02-19 17:43 UTC, irfansharif commented on cmd/storage-server/server.go
> +	Keys(cancel <-chan struct{}) <-chan string
I would change this API (down to the `diskv` implementation) to simply return a slice of strings, and not taking any cancellation struct.

2019-02-19 17:43 UTC, irfansharif commented on cmd/metadata-server/server.go
> +	for key := range fileKeysRes.Keys {
```suggestion
	for _, key := range fileKeysRes.Keys {
	  // No longer need 'actualKey ...'
```

2019-02-19 17:43 UTC, irfansharif commented on cmd/metadata-server/server.go
> +			metadata, err := s.getMetadataFile(ctx)
Isn't all this unnecessary? By definition these files aren't present in metadata, so why try to delete and reset metadata? It'll be unchanged.

2019-02-19 17:43 UTC, irfansharif commented on pkg/pb/metadata/metadata.proto
> +    rpc ForceGarbageCollection (ForceGarbageCollectionRequest) returns (ForceGarbageCollectionResponse);
This should not be in the public API, we're only using this to test. Here's what to do instead:

```go
// Within cmd/metadata-server/server.go

// To only be used for testing purposes.
func TestForceGC(s *Server) error {
	return s.runGarbageCollection(context.Background())
}
```

Now you no longer need the proto changes.

2019-02-21 04:43 UTC, arhamahmed commented
Did some cleanup, should be good to go now.

2019-02-21 04:46 UTC, merged